### ISSUE TITLE
npe in instantanswers adapter

### ISSUE THREAD

**Issue by rothschild86** [uservoice/uservoice-android-sdk#137]
Seeing this npe in my reports... http://crashes.to/s/961866b9d9e/details

https://github.com/uservoice/uservoice-android-sdk/blob/master/UserVoiceSDK/src/com/uservoice/uservoicesdk/ui/InstantAnswersAdapter.java hasn't changed in 6 months, so I assume the issue is still there.

**Comment by austintaylor** [comment]
Null check added in 1.2.1
