### ISSUE TITLE
Error:Execution failed for task ':androidCollapsibleSearchMenuLibrary:processDebugTestManifest'.

### ISSUE THREAD

**Issue by Jakevin** [uservoice/uservoice-android-sdk#138]
I first time user this SDK, then get this question

Error:Execution failed for task ':androidCollapsibleSearchMenuLibrary:processDebugTestManifest'.
> java.lang.RuntimeException: Manifest merger failed : uses-sdk:targetSdkVersion 15 cannot be different than version L declared in library com.android.support:support-v4:21.0.0-rc1

my gradle setting
compileSdkVersion 'android-L'
    buildToolsVersion '20.0.0'

    defaultConfig {
        applicationId "com.accuvally.android.accupass"
        minSdkVersion 14
        targetSdkVersion "L"
   }
dependencies {
    compile 'com.android.support:support-v4:21.+'
    compile 'com.android.support:appcompat-v7:21.+'
    compile 'com.android.support:support-v13:21.+'
    //Uservoice
    compile 'com.uservoice:uservoice-android-sdk:1.+'
}

**Comment by austintaylor** [comment]
Support for api 21 was added in 1.2.0
