### ISSUE TITLE
Long description: There was an error connecting to UserVoice

### ISSUE THREAD

**Issue by alexblack** [uservoice/uservoice-android-sdk#149]
If the user writes a lot of text, then UserVoice fails to submit their feedback, and displays the error "There was an error connecting to UserVoice".

Instead, I expected the feedback to be submittted.

A user of mine reported the problem here: http://invoicemaker.uservoice.com/forums/273867-general/suggestions/6772190-see-next-input-window

Here is a screenshot of it happening to me:

![2014-11-27 18 52 41](https://cloud.githubusercontent.com/assets/148930/5220960/c0b99278-7623-11e4-9e9f-1523fbee64a5.png)

Steps to recreate:

1. Invoke UserVoice.launchPostIdea
2. Write a lot of text in the suggestion box, hit next
3. Write a lot of text in the desc box
4. Hit submit

**Comment by austintaylor** [comment]
Fixed in 1.2.1

**Comment by jaypandya** [comment]
This same issue also appears in Contact Us page.
