### ISSUE TITLE
NPE in PortalAdapter.getCount()

### ISSUE THREAD

**Issue by apkelly** [uservoice/uservoice-android-sdk#151]
com.uservoice.uservoicesdk.ui.PortalAdapter.getCount (PortalAdapter.java:139)
com.uservoice.uservoicesdk.ui.PortalAdapter.getView (PortalAdapter.java:265)
android.widget.AbsListView.obtainView (AbsListView.java:2240)
android.widget.ListView.makeAndAddView (ListView.java:1790)
android.widget.ListView.fillUp (ListView.java:725)
android.widget.ListView.fillGap (ListView.java:664)
android.widget.AbsListView.trackMotionScroll (AbsListView.java:5136)
android.widget.AbsListView.scrollIfNeeded (AbsListView.java:3236)
android.widget.AbsListView.onTouchMove (AbsListView.java:3580)
android.widget.AbsListView.onTouchEvent (AbsListView.java:3424)
android.view.View.dispatchTouchEvent (View.java:7837)
android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:2210)

I'm not sure what the latest version is, but here is our Gradle config for UserVoice.

    compile(group: 'com.uservoice', name: 'uservoice-android-sdk', version: '1.1+') {
        exclude(group: 'org.apache.httpcomponents', module: 'httpclient')
        exclude(group: 'com.android.support', module: 'appcompat-v7')
    }

The device that reported the crash through Crashlytics was a Sony Xperia Z2 running Android 4.4.2.

**Comment by austintaylor** [comment]
Fixed in 1.2.1
