### ISSUE TITLE
Duplicate dependencies

### ISSUE THREAD

**Issue by shafty023** [uservoice/uservoice-android-sdk#163]
It looks like you are not filtering out dependencies in your build.gradle files.

**./gradlew -q dependencies**

```
com.uservoice:uservoice-android-sdk:+ -> 1.2.2
|    |    +--- commons-codec:commons-codec:1.8
|    |    +--- oauth.signpost:signpost-commonshttp4:1.2.1.2
|    |    |    +--- oauth.signpost:signpost-core:1.2.1.2
|    |    |    |    \--- commons-codec:commons-codec:1.3 -> 1.8
|    |    |    +--- org.apache.httpcomponents:httpcore:4.0.1
|    |    |    \--- org.apache.httpcomponents:httpclient:4.0.1
|    |    |         +--- org.apache.httpcomponents:httpcore:4.0.1
|    |    |         +--- commons-logging:commons-logging:1.1.1
|    |    |         \--- commons-codec:commons-codec:1.3 -> 1.8
|    |    +--- com.android.support:appcompat-v7:21.+ -> 21.0.3
|    |    |    \--- **com.android.support:support-v4:21.0.3 (*)**
|    |    +--- **oauth.signpost:signpost-core:1.2.1.2 (*)**
|    |    \--- com.android.support:support-v4:21. -> 21.0.3 (*)
```

So AppCompat v7 already includes support-v4 yet you have it defined as its own dependency. Same goes for signpost-core which is included in signpost-commonshttp4 but you have it declared separately as a dependency. Can you fix your dependency management in build.gradle to correctly exclude these additional modules?

**New version of UserVoiceSDK/build.gradle**

```
dependencies {
    compile 'com.android.support:appcompat-v7:21.+'
    compile 'commons-codec:commons-codec:1.8'
    compile ('oauth.signpost:signpost-commonshttp4:1.2.1.2') {
        exclude module: 'commons-logging'
        exclude module: 'httpcore'
        exclude module: 'httpclient'
    }
}
```

This removes the duplicate dependencies that are already included as a transient dependency elsewhere. Or you can exclude these as transient dependencies and keep them declared in your own build.gradle file. Either way it should be cleaned up.

**Comment by austintaylor** [comment]
This is done.
