### ISSUE TITLE
AIR Application Runtime Error

### ISSUE THREAD

**Issue by jwoodesg** [uservoice/uservoice-android-sdk#167]
Hello, we are trying to implement the SDK, building with ANT. As a Starling project, our compiled jar lives in an ANE.

We are using an FREContext that initializes and launches UserVoice as per your documentation. However, we receive a crash when we try to call launchUserVoice. With unchanged source code, we receive a java.lang.NoClassDefFoundError: com.uservoice.uservoicesdk.activity.PortalActivity. The imports are there. We even tried importing the activities from the callers.

We have the activities declared in our (Starling-android) manifest; like how UserVoice's AndroidManifest is configured.

We have tried using a service so the activity could be launched from a new intent, coming from the application context, but still receive the same error.

We have even tried taking all of the UserVoice SDK source code and putting it all in our company's package, renaming all of the package definitions and imports; but still receive the same error.

I'm curious if you have any suggestions or if you've encountered this problem before.

thanks!!

**Comment by austintaylor** [comment]
It sounds like the class is not making it into your classes.dex. I don't know enough about ANEs to know what to do about that, but Googling around finds others having the same problem with ANEs and 3rd party libraries.

**Comment by jwoodesg** [comment]
Do you have a jar that we can just include as a packaged dependency? Perhaps our issue is related to the way ANT compiles the code.

**Comment by jwoodesg** [comment]
We use many external libraries in our project and have never needed to modify source code. All we need is a jar, if you could make that available.
