### ISSUE TITLE
java.lang.NullPointerException in ArrayAdapter?

### ISSUE THREAD

**Issue by Trebia** [uservoice/uservoice-android-sdk#174]
Dear all,

I have received the following exception during app usage in production, wihtout any clue of what's happening.

Any idea? Is a real issue?

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mypackage/com.uservoice.uservoicesdk.activity.TopicActivity}: java.lang.NullPointerException
1	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1706)
2	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1723)
3	at android.app.ActivityThread.access$1500(ActivityThread.java:118)
4	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:948)
5	at android.os.Handler.dispatchMessage(Handler.java:99)
6	at android.os.Looper.loop(Looper.java:130)
7	at android.app.ActivityThread.main(ActivityThread.java:3756)
8	at java.lang.reflect.Method.invokeNative(Native Method)
9	at java.lang.reflect.Method.invoke(Method.java:507)
10	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
11	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
12	at dalvik.system.NativeStart.main(Native Method)
13	Caused by: java.lang.NullPointerException
14	at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:291)
15	at android.support.v7.internal.widget.AbsSpinnerCompat.setAdapter(AbsSpinnerCompat.java:95)
16	at android.support.v7.internal.widget.SpinnerCompat.setAdapter(SpinnerCompat.java:360)
17	at android.support.v7.internal.widget.ToolbarWidgetWrapper.setDropdownParams(ToolbarWidgetWrapper.java:561)
18	at android.support.v7.internal.app.WindowDecorActionBar.setListNavigationCallbacks(WindowDecorActionBar.java:1244)
19	at com.uservoice.uservoicesdk.activity.TopicActivity.onCreate(TopicActivity.java:38)
20	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1073)
21	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1653)
22	... 11 more
23	java.lang.NullPointerException
24	at android.widget.ArrayAdapter.getCount(ArrayAdapter.java:291)
25	at android.support.v7.internal.widget.AbsSpinnerCompat.setAdapter(AbsSpinnerCompat.java:95)
26	at android.support.v7.internal.widget.SpinnerCompat.setAdapter(SpinnerCompat.java:360)
27	at android.support.v7.internal.widget.ToolbarWidgetWrapper.setDropdownParams(ToolbarWidgetWrapper.java:561)
28	at android.support.v7.internal.app.WindowDecorActionBar.setListNavigationCallbacks(WindowDecorActionBar.java:1244)
29	at com.uservoice.uservoicesdk.activity.TopicActivity.onCreate(TopicActivity.java:38)
30	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1073)
31	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1653)
32	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1723)
33	at android.app.ActivityThread.access$1500(ActivityThread.java:118)
34	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:948)
35	at android.os.Handler.dispatchMessage(Handler.java:99)
36	at android.os.Looper.loop(Looper.java:130)
37	at android.app.ActivityThread.main(ActivityThread.java:3756)
38	at java.lang.reflect.Method.invokeNative(Native Method)
39	at java.lang.reflect.Method.invoke(Method.java:507)
40	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
41	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
42	at dalvik.system.NativeStart.main(Native Method)

**Comment by austintaylor** [comment]
Dup of #112
