### ISSUE TITLE
gradle not building/and cannot resolve symbol R in all the java files..been trying to solve for days

### ISSUE THREAD

**Issue by Qiqie** [uservoice/uservoice-android-sdk#178]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugTestSources, :fadingactionbarlibrary:generateDebugSources, :fadingactionbarlibrary:generateDebugTestSources, :HoloGraphLibrary:generateDebugSources, :HoloGraphLibrary:generateDebugTestSources, :jlpsiLocal:generateDebugSources, :jlpsiLocal:generateDebugTestSources]
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debugTest as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
Warning:Dependency org.apache.httpcomponents:httpclient:4.0.1 is ignored for release as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages
:app:preBuild
:app:preDebugBuild
:app:checkDebugManifest
:HoloGraphLibrary:compileLint
:HoloGraphLibrary:copyReleaseLint UP-TO-DATE
:HoloGraphLibrary:mergeReleaseProguardFiles UP-TO-DATE
:HoloGraphLibrary:preBuild
:HoloGraphLibrary:preReleaseBuild
:HoloGraphLibrary:checkReleaseManifest
:HoloGraphLibrary:prepareReleaseDependencies
:HoloGraphLibrary:compileReleaseAidl UP-TO-DATE
:HoloGraphLibrary:compileReleaseRenderscript UP-TO-DATE
:HoloGraphLibrary:generateReleaseBuildConfig UP-TO-DATE
:HoloGraphLibrary:generateReleaseAssets UP-TO-DATE
:HoloGraphLibrary:mergeReleaseAssets UP-TO-DATE
:HoloGraphLibrary:generateReleaseResValues UP-TO-DATE
:HoloGraphLibrary:generateReleaseResources UP-TO-DATE
:HoloGraphLibrary:packageReleaseResources UP-TO-DATE
:HoloGraphLibrary:processReleaseManifest UP-TO-DATE
:HoloGraphLibrary:processReleaseResources UP-TO-DATE
:HoloGraphLibrary:generateReleaseSources UP-TO-DATE
:HoloGraphLibrary:compileReleaseJava UP-TO-DATE
:HoloGraphLibrary:processReleaseJavaRes UP-TO-DATE
:HoloGraphLibrary:packageReleaseJar UP-TO-DATE
:HoloGraphLibrary:compileReleaseNdk UP-TO-DATE
:HoloGraphLibrary:packageReleaseJniLibs UP-TO-DATE
:HoloGraphLibrary:packageReleaseLocalJar UP-TO-DATE
:HoloGraphLibrary:packageReleaseRenderscript UP-TO-DATE
:HoloGraphLibrary:bundleRelease UP-TO-DATE
:app:preReleaseBuild
:fadingactionbarlibrary:compileLint
:fadingactionbarlibrary:copyReleaseLint UP-TO-DATE
:fadingactionbarlibrary:preBuild
:fadingactionbarlibrary:preReleaseBuild
:fadingactionbarlibrary:checkReleaseManifest
:fadingactionbarlibrary:preDebugBuild
:fadingactionbarlibrary:preDebugTestBuild
:fadingactionbarlibrary:prepareComAndroidSupportAppcompatV72000Library UP-TO-DATE
:fadingactionbarlibrary:prepareComAndroidSupportSupportV42000Library UP-TO-DATE
:fadingactionbarlibrary:prepareReleaseDependencies
:fadingactionbarlibrary:compileReleaseAidl
:fadingactionbarlibrary:compileReleaseRenderscript UP-TO-DATE
:fadingactionbarlibrary:generateReleaseBuildConfig UP-TO-DATE
:fadingactionbarlibrary:generateReleaseAssets UP-TO-DATE
:fadingactionbarlibrary:mergeReleaseAssets UP-TO-DATE
:fadingactionbarlibrary:generateReleaseResValues UP-TO-DATE
:fadingactionbarlibrary:generateReleaseResources UP-TO-DATE
:fadingactionbarlibrary:mergeReleaseResources
:fadingactionbarlibrary:processReleaseManifest UP-TO-DATE
:fadingactionbarlibrary:processReleaseResources
:fadingactionbarlibrary:generateReleaseSources
:fadingactionbarlibrary:compileReleaseJava UP-TO-DATE
:fadingactionbarlibrary:extractReleaseAnnotations UP-TO-DATE
:fadingactionbarlibrary:mergeReleaseProguardFiles UP-TO-DATE
:fadingactionbarlibrary:processReleaseJavaRes UP-TO-DATE
:fadingactionbarlibrary:packageReleaseJar UP-TO-DATE
:fadingactionbarlibrary:compileReleaseNdk UP-TO-DATE
:fadingactionbarlibrary:packageReleaseJniLibs UP-TO-DATE
:fadingactionbarlibrary:packageReleaseLocalJar UP-TO-DATE
:fadingactionbarlibrary:packageReleaseRenderscript UP-TO-DATE
:fadingactionbarlibrary:packageReleaseResources UP-TO-DATE
:fadingactionbarlibrary:bundleRelease UP-TO-DATE
:jlpsiLocal:compileLint
:jlpsiLocal:copyReleaseLint UP-TO-DATE
:jlpsiLocal:preBuild
:jlpsiLocal:preReleaseBuild
:jlpsiLocal:checkReleaseManifest
:jlpsiLocal:preDebugBuild
:jlpsiLocal:preDebugTestBuild
:jlpsiLocal:prepareComAndroidSupportSupportV42200Library
:jlpsiLocal:prepareReleaseDependencies
:jlpsiLocal:compileReleaseAidl
:jlpsiLocal:compileReleaseRenderscript UP-TO-DATE
:jlpsiLocal:generateReleaseBuildConfig UP-TO-DATE
:jlpsiLocal:generateReleaseAssets UP-TO-DATE
:jlpsiLocal:mergeReleaseAssets UP-TO-DATE
:jlpsiLocal:generateReleaseResValues UP-TO-DATE
:jlpsiLocal:generateReleaseResources UP-TO-DATE
:jlpsiLocal:mergeReleaseResources UP-TO-DATE
:jlpsiLocal:processReleaseManifest UP-TO-DATE
:jlpsiLocal:processReleaseResources UP-TO-DATE
:jlpsiLocal:generateReleaseSources
:jlpsiLocal:compileReleaseJava
:jlpsiLocal:extractReleaseAnnotations
:jlpsiLocal:mergeReleaseProguardFiles UP-TO-DATE
:jlpsiLocal:processReleaseJavaRes UP-TO-DATE
:jlpsiLocal:packageReleaseJar UP-TO-DATE
:jlpsiLocal:compileReleaseNdk UP-TO-DATE
:jlpsiLocal:packageReleaseJniLibs UP-TO-DATE
:jlpsiLocal:packageReleaseLocalJar UP-TO-DATE
:jlpsiLocal:packageReleaseRenderscript UP-TO-DATE
:jlpsiLocal:packageReleaseResources UP-TO-DATE
:jlpsiLocal:bundleRelease UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72200Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42200Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServices700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAds700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAnalytics700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAppindexing700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesAppstate700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesBase700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesCast700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesDrive700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesFitness700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGames700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesGcm700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesIdentity700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesLocation700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesMaps700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesNearby700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesPanorama700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesPlus700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesSafetynet700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesWallet700Library UP-TO-DATE
:app:prepareComGoogleAndroidGmsPlayServicesWearable700Library UP-TO-DATE
:app:prepareJlpsiFadingactionbarlibraryUnspecifiedLibrary UP-TO-DATE
:app:prepareJlpsiHoloGraphLibraryUnspecifiedLibrary UP-TO-DATE
:app:prepareJlpsiJlpsiLocalUnspecifiedLibrary UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources
C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\src\main\res\drawable-hdpi\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\src\main\res\drawable-xhdpi\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\res\drawable-hdpi-v4\abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\src\main\res\drawable-mdpi\ic_drawer.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
:app:processDebugManifest
C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\src\main\AndroidManifest.xml:0:0 Error:
	uses-sdk:minSdkVersion 3 cannot be smaller than version 7 declared in library C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="android.support.v7.appcompat" to force usage
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 3 cannot be smaller than version 7 declared in library C:\Users\J Myk\AndroidStudioProjects\Jlpsi\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\22.0.0\AndroidManifest.xml
	Suggestion: use tools:overrideLibrary="android.support.v7.appcompat" to force usage
Information:BUILD FAILED
Information:Total time: 11 mins 54.01 secs
Information:1 error
Information:5 warnings
Information:See complete output in console

**Comment by austintaylor** [comment]
The UserVoice SDK has minSdkVersion="8" and v7.appcompat (which we depend on) has minSdkVersion="7". I don't think it will work with your app as long as it has minSdkVersion="3".
