### ISSUE TITLE
"There was an error connecting to UserVoice" on first launch

### ISSUE THREAD

**Issue by mariciv** [uservoice/uservoice-android-sdk#179]
When I try to launch UserVoice for the first time it shows popup "There was an error connecting to UserVoice"

In logcat I see these lines of log connected to the error:
D/UV﹕ /api/v1/clients/default.json
D/UV﹕ https://by.uservoice.com/t/k/htm2/d/k/track.js?_=1429188488937&c=_
E/com.uservoice.uservoicesdk﹕ Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference -- null 

After I go back and try again it launches UserVoice normally.

**Comment by ChrisMCMine** [comment]
Related to #170

**Comment by austintaylor** [comment]
This was caused by a server-side issue that was fixed on Apr 29 2015.
