### ISSUE TITLE
Instant answers pulled from all forums

### ISSUE THREAD

**Issue by jmpilot** [uservoice/uservoice-android-sdk#185]
In ourUV demo app, I setup joeyp.uservoice.com. I have 2 forums - General and Specific.

General forum: http://joeyp.uservoice.com/forums/288284-general 
Specific forum: http://joeyp.uservoice.com/forums/299022-specific

General is the forum that is setup in the SDK: http://screencast.com/t/ryLMFJXy4 
when I type "specific" I get ideas that are in the Specific forum: http://screencast.com/t/4VvHLI38I

**Comment by austintaylor** [comment]
Server-side issue.
