### ISSUE TITLE
Problem with signature verification.

### ISSUE THREAD

**Issue by bratislavdamnjanovic** [uservoice/uservoice-android-sdk#222]
Hi,

I'm having a problem.
401 -- {"errors":{"message":"Signed client required: Signature verification failed","type":"unauthorized"}}

I'm starting it with:
final Config config = new Config(rs.intellex.studio.Config.getString(R.string.__user_voice_url, this));
config.identifyUser(User.getId(this), User.getFirstName(this) + " " + User.getLastName(this), User.getEmail(this)); UserVoice.init(config, this);

And the error is triggered after "I want this!" or when posting idea.
In the logcat it occurs after /api/v1/users.json

Thanks

**Comment by austintaylor** [comment]
Fixed in master + 1.2.5.

**Comment by Hamoda37** [comment]
// Set this up once when your application launches
Config config = new Config("hamo.uservoice.com");
config.setShowContactUs(false);
config.setShowKnowledgeBase(false);
config.setForumId(354351);
// config.identifyUser("USER_ID", "User Name", "email@example.com");
UserVoice.init(config, this);

// Call this wherever you want to launch UserVoice
UserVoice.launchForum(this);
