### ISSUE TITLE
ActionBarActivity removed from SupportLib 26

### ISSUE THREAD

**Issue by noho13** [uservoice/uservoice-android-sdk#247]
have a look here:
https://developer.android.com/sdk/support_api_diff/26.0.0-beta2/changes.html

Is there any update for the sdk planned? 

Thanks

**Comment by mtrakal** [comment]
some parts are prepared in: https://github.com/mtrakal/uservoice-android-sdk/tree/feature/tabLayout but I don't have time to understand a non-layout view, how to inflate toolbar into actionbar in this too-old source codes...

**Comment by bafitor** [comment]
Support library was released yesterday:

**Comment by bafitor** [comment]
Support Library 26 was released yesterday and we can't update our app because UserVoice will crash with the new version.

https://developer.android.com/topic/libraries/support-library/revisions.html

Any updates regarding this issue?

**Comment by mtrakal** [comment]
I contact UserVoice custommer support now. Hope for some reaction...

**Comment by austintaylor** [comment]
Fixed in 1.2.6
