### ISSUE TITLE
Support for Android O

### ISSUE THREAD

**Issue by jmpilot** [uservoice/uservoice-android-sdk#250]

**Comment by caltseng** [comment]
+1

**Comment by billge** [comment]
+1

**Comment by billge** [comment]
@austintaylor I noticed the PR was merged. Will you be creating a new release for it?

**Comment by caltseng** [comment]
Wow thanks @billge !

**Comment by billge** [comment]
@austintaylor I can't seem to find the new release on jcenter?
https://bintray.com/austintaylor/maven/com.uservoice%3Auservoice-android-sdk

**Comment by austintaylor** [comment]
@billge Looks like I forgot to hit Publish. It should be there now. Thanks for the PR!
