### ISSUE TITLE
Public APIs for NPS

### ISSUE THREAD

**Issue by peeyuuec** [uservoice/uservoice-android-sdk#257]
I was using uservoice android sdk for user suggestions. We are making a move to use APIs to send suggestions to our forum. I didn't see any API to send NPS data. On the uservoice admin portal, I can see a tab for NPS. How to send NPS data using APIs?

**Comment by austintaylor** [comment]
This is possible using our v2 API: https://developer.uservoice.com/docs/api/v2/reference/#?q=nps
