### ISSUE TITLE
NPE on resume

### ISSUE THREAD

**Issue by rothschild86** [uservoice/uservoice-android-sdk#54]
If user browses uservoice activity, leaves the device alone for a while with uservoice on the screen, and comes back later, they'll be greeted with a null ref crash.

11-16 22:56:40.947: E/AndroidRuntime(31530): FATAL EXCEPTION: main
11-16 22:56:40.947: E/AndroidRuntime(31530): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stuffd/com.uservoice.uservoicesdk.activity.PortalActivity}: java.lang.NullPointerException

11-16 22:56:40.947: E/AndroidRuntime(31530): Caused by: java.lang.NullPointerException
11-16 22:56:40.947: E/AndroidRuntime(31530): 	at com.uservoice.uservoicesdk.model.ClientConfig.loadClientConfig(ClientConfig.java:28)

I assume the activity gets destroyed, and then not recreated properly (config becomes null).

**Comment by phileo** [comment]
@agois I am not clear on how method #2 would work - perhaps you can show us with a code snippet on how to use onSaveInstance() to save the Config.userTraits.

**Comment by austintaylor** [comment]
I believe this was fixed by 03f4ee0ba
